name: Publish NuGet.org

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: windows-latest
    name: Update package

    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      
      - name: User .NET 3.1.100
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100
        
      - name: Building
        run: |
          dotnet msbuild MathCore.WPF\MathCore.WPF.csproj -noConLog -nologo
          dotnet msbuild Tests\MathCore.WPF.Tests\MathCore.WPF.Tests.csproj -noConLog -nologo
          
      - name: Testing
        run: dotnet test Tests\MathCore.WPF.Tests\MathCore.WPF.Tests.csproj
        
      - name: Packing
        run: dotnet pack MathCore.WPF\MathCore.WPF.csproj -c Release -v q
        
      - name: Publishing
        run: |
          dir
          dir MathCore.WPF
          dir MathCore.WPF\bin
          dir MathCore.WPF\bin\Release
          dir MathCore.WPF\bin\Release\*.nupkg
          dotnet nuget push MathCore.WPF\bin\Release\*.nupkg -k ${{ secrets.NuGetApiKey }} -n -SkipDuplicate -s https://api.nuget.org/v3/index.json
