name: Publish NuGet.org

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: windows-latest
    name: Update package

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Use .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
        
      - name: Building
        run: |
          dotnet build MathCore.WPF -c Release
          dotnet build Tests\MathCore.WPF.Tests -c Release
          
      - name: Testing
        run: dotnet test Tests\MathCore.WPF.Tests -c Release --no-build
        
      - name: Packing
        run: dotnet pack MathCore.WPF --no-build -c Release -v q
        
      - name: Publishing
        run: dotnet nuget push "**/*.nupkg" -k ${{ secrets.NuGetApiKey }} --skip-duplicate -s https://api.nuget.org/v3/index.json
