name: Testing

on:
  push:
    branches: 
    - '*'
    paths-ignore: 
    - '.github/workflows/**'
    - '**.md'
    - '**.docx'
    - '**.bat'
    - '**.vssettings'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

jobs:
  test:
    name: Testing
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          
      - name: Building
        run: |
          dotnet build MathCore.WPF -c Debug
          dotnet build Tests/MathCore.WPF.Tests -c Debug
          
      - name: Run Tests
        run: dotnet test Tests/MathCore.WPF.Tests -c Debug --no-build
